main: com.winthier.shutdown.ShutdownPlugin
name: Shutdown

version: 0.1
api-version: '1.20'

description: Automated shutdown service
author: StarTux
website: https://github.com/StarTux/Shutdown

depend: [Core, Connect]
softdepend: []

commands:
  shutdown:
    description: Admin interface
    permission: shutdown.shutdown
    usage: |-
      Usage: /shutdown
      /shutdown <seconds> - Initiate shutdown
      /shutdown now - Shutdown with a nice interval
      /shutdown info - Print performance and timing information
      /shutdown reload - Reload the configuration file
      /shutdown reset - Reset all shutdown timings
      /shutdown cancel - Cancel the currently ongoing shutdown
      /shutdown dump - Dump thread stack traces
      /shutdown whenempty - Shutdown next time the server is empty
permissions:
  shutdown.shutdown:
    description: Use the /shutdown command
    default: op
  shutdown.alert:
    description: Alert when a shutdown reason occurs
    default: op
  shutdown.notify:
    description: Receive shutdown broadcasts and titles
    default: true
